### ISSUE TITLE
Java - `turnRight` and `turnLeft` never stop turning if last function

### ISSUE THREAD

**Issue by beamer159** [robocode-dev/tank-royale#23]
Version: Java

If the last function called in `run` is `turnLeft` or `turnRight`, the robot turns and never stops turning. If another function (e.g. `forward`) follows one of these two functions, the robot stops turning and performs the next action, as expected.

Some thoughts. This is similar to #17, which was recently fixed for `forward` and `back`. Now, these two functions are experiencing another issue in #22. When this problem with `turnLeft` and `turnRight` is looked at, hopefully the solution does not lead to similar #22 issues.

**Comment by flemming-n-larsen** [comment]
You are right @beamer159,

This sure sound similar to to the forward/back issue even when they funtion a bit different.

I guess I will need to setup some test with various "bots" moving differently, so we can catch these kinds of bugs in the future when doing adjustments.

Thank you for reporting this, and keep up the good work. We need to get rid of the "child sickness" in the new version of the game while it is still in "alpha" version. 🙂

**Comment by flemming-n-larsen** [comment]
I can add, that this bug is also present for turning the gun and radar the same way.

**Comment by flemming-n-larsen** [comment]
This bug has now been found and solved for both the JVM and .Net version of the Bot API.
The fix will be available with the next release.

**Comment by flemming-n-larsen** [comment]
Fix is available with [release 0.13.1](https://github.com/robocode-dev/tank-royale/releases/tag/v0.13.1)

**Comment by beamer159** [comment]
Hmm, I am still getting the same behavior.

```
public void run() {
    turnRight(360);
}
```

This program turns indefinitely for me.

**Comment by flemming-n-larsen** [comment]
Confirmed. This bug was fixed, but was reintroduced when improving/fixing the event queue.
Because the blocking call does not return as it continues for infitity, events are queued up on the event queue as those are not processed.

I will look into fixing this ASAP.

**Comment by flemming-n-larsen** [comment]
[Release 0.13.2](https://github.com/robocode-dev/tank-royale/releases/tag/v0.13.2) should finally fix this issue. I tested it thoroughly for bot the Java and .Net API. 🤞

**Comment by beamer159** [comment]
Looks good, thanks
